[terminal.sexy]
text={{>foreground}}
text(bold)={{>foreground}}
background={{>background}}
black={{>0}}
black(bold)={{>8}}
red={{>1}}
red(bold)={{>9}}
green={{>2}}
green(bold)={{>10}}
yellow={{>3}}
yellow(bold)={{>11}}
blue={{>4}}
blue(bold)={{>12}}
magenta={{>5}}
magenta(bold)={{>13}}
cyan={{>6}}
cyan(bold)={{>14}}
white={{>7}}
white(bold)={{>15}}
[Names]
name0={{@}}
count=1
